// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IExceptionService is an autogenerated mock type for the IExceptionService type
type IExceptionService struct {
	mock.Mock
}

// SaveException provides a mock function with given fields: ctx, exceptionMsg
func (_m *IExceptionService) SaveException(ctx context.Context, exceptionMsg string) error {
	ret := _m.Called(ctx, exceptionMsg)

	if len(ret) == 0 {
		panic("no return value specified for SaveException")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, exceptionMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIExceptionService creates a new instance of IExceptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExceptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExceptionService {
	mock := &IExceptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
