// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IPasswordGenerator is an autogenerated mock type for the IPasswordGenerator type
type IPasswordGenerator struct {
	mock.Mock
}

// NewPassword provides a mock function with given fields: ctx
func (_m *IPasswordGenerator) NewPassword(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewPassword")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIPasswordGenerator creates a new instance of IPasswordGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPasswordGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPasswordGenerator {
	mock := &IPasswordGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
