// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IEventPublisher is an autogenerated mock type for the IEventPublisher type
type IEventPublisher struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: ctx, message
func (_m *IEventPublisher) SendMessage(ctx context.Context, message string) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIEventPublisher creates a new instance of IEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEventPublisher {
	mock := &IEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
